print("Hello, world!")
print("Hello,\n\nworld!")
print(3)
print(2,5)
print(2+5)
print('The number is',4)
print('The number is', str(4))
print('Monday\tTuesday\tWednesday')
print(16,17,18)
print('16\t17\t18')
print(1.234567899874889589604865)
print('What\s your name?')
print('What\s your name?')
print('I said, "Who are you"')
print('I said, "Who are you"')
print('This is going to be a very long string inside the print function call. Will it work?')
print('This is going to be a very long string inside the print function','call.  Will it work?')
